### ISSUE TITLE
Roll initiative when adding creatures from the Encounter Table to an existing encounter

### ISSUE THREAD

**Issue by cjolson** [javalent/initiative-tracker#81]
When choosing "Add to Encounter" from an Encounter Table (instead of "Begin Encounter", all creatures are added with an initiative dice roll of 0. It would be nice if their initiative was rolled when added so I don't have to roll and adjust each manually (especially if I added a lot of creatures).

**Comment by Chr9sG** [comment]
I have the same issue. The work around I use for this is to add all the creatures in and then just use the "re-roll initiative" to roll all the participants initiative in a single go. Then I adjust the players (since I let the players roll their own initiative).
![Reroll initiatives](https://user-images.githubusercontent.com/97812598/200203095-c0ddbe36-6703-44ab-b922-f5116fb7bda5.jpg)

**Comment by cjolson** [comment]
I did see that as an options, though this is less ideal if you’re adding people to an existing encounter (i.e. “the reinforcements arrived” or “creatures in the other room heard the fighting”). In that instance, I my workaround is to adjust the new combatants’ initiatives manually.

**Comment by andrgram** [comment]
I'd like to revive this one as it would be a very nice feature when adding planned reinforcements to an encounter
